[package]
name = "connect4"
version = "0.1.0"
edition = "2021"
authors = [
  "Romain Ageron",
  "Thomas Brilland",
]


[[bin]]
name = "connect4_client"
path = "src/client/main.rs"

[[bin]]
name = "connect4_server"
path = "src/server/main.rs"


[dependencies]
clap = "3.1.18"
rand = "0.8.5"
